//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTask1EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlatformTypeInGame
    {
        public string PlatformTypeInGameKey { get; set; }
        public string PlatformTypeKey { get; set; }
        public string GameKey { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual PlatformType PlatformType { get; set; }
    }
}
