//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTaskEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public string OrderDetailsKey { get; set; }
        public string GameKey { get; set; }
        public string CustomersOrderKey { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<float> Discount { get; set; }
    
        public virtual CustomersOrder CustomersOrder { get; set; }
        public virtual Game Game { get; set; }
    }
}
